app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    
login:
    path: /login
    
logout:
    path: /logout
    
account:
    path: /account
    
admin:
    path: /admin

products_management:
    path: /admin/products
    
products_add:
    path: /admin/products/add
    
products_edit:
    path: /admin/products/edit
    
ingredients_management:
    path: /admin/products/ingredient

ingredients_add:
    path: /admin/products/ingredient/add
    
cart:
    path: /cart
    
cart_add:
    path: /cart/add
    
cart_flush:
    path: /cart/flush

cart_product_remove:
    path: /cart/remove
    
order:
    path: /order
    
order_finalize:
    path: /order/finalize